### PR TITLE
Cheat sheet and hex

### LINKED ISSUE #4: Pull Phylogeny from PhyloPic
Re this: "I plan to be able to get a phylogeny for taxa associatd with Phylopic silhouettes using the NCBI taxonomy, but it's not easily available yet"

You could pull the phylogeny from PhyloPic itself. Granted, it's not as clean overall as NCBI, but it is usually at least as good for illustrated taxa (sometimes better).

Here's the relevant method: http://phylopic.org/api/#method-name-taxonomy

### PR DESCRIPTION
**Pull request by GabsPalomo**
## Description

I am uploading a folder which contains the cheat sheet for rphylopic and the hex sticker .png file. I designed and created both files.

### CODE REVIEW

**Comment by sckott** [comment]
thanks @GabsPalomo ! i'm asking around where folks usually put cheatsheets in a package. 🕐

**Comment by sckott** [comment]
hey again, so i think this should work. make these changes on your version and push up, and those changes should appear here

- create a folder `vignettes` in the root of the pkg
- move the cheatsheet pdf into the `vignettes` folder, and rename to `cheatsheet.pdf`
- add a file in `vignettes` called `cheatsheet.Rmd` and put into that file:

```r
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{rphylopic cheatsheet}
%\VignetteEncoding{UTF-8}
```

Add to DESCRIPTION file:

```
VignetteBuilder: knitr
```

and add `knitr` to Suggests

for the image file: 

- can you change file name to `logo.png`
- move the file into the folder `man/figures` like this one https://github.com/ropensci/rgbif/blob/master/man/figures/logo.png (you'll probably have to create the `figures` folder)

**Comment by GabsPalomo** [comment]
Just added the cheat sheet and logo per your instructions. Hope it's all good. Now I can send everyone here to download the cheat sheet. And if it needs to be updated then I can upload new versions here.

**Comment by sckott** [comment]
thanks, looks good to me!

**Pull request merged**
