### PR TITLE
Added base plotting for phylopic

### PR DESCRIPTION
**Pull request by dill**
Uses `gridBase` to add phylopics to base graphics.

 * new function `add_phylopic_base` (maybe the function name should be changed?)
 * new function: `recolor_phylopic`, pulled out the colouring/alpha code from `add_phylopic*`
 * new dependency: `gridBase` to make sure we can plot on a base graphics plot

### CODE REVIEW

**Comment by richfitz** [comment]
While you're there, do you see any overlap with [this](https://github.com/richfitz/vectoR) - I started working on this to get phylopic svg images into plots but I don't ggplot so didn't really know how to close the loop.  The recolour bit is probably similar...

**Comment by dill** [comment]
At the moment `rphylopic` just deals with PNG files, not fancypants SVG (AFAIK, @sckott please correct me if I'm being stupid). So it just relies on interpolation (provided in `grid.raster`) to draw bigger images.

This PR was just from some quick code I needed to produce an animation for useR!, but it seems like this would be a cool addition, especially for publication graphics.

**Comment by sckott** [comment]
@richfitz nice! how easy is it to get inkscape and ghostscript across platforms? Would be nice to have svg support for sure. I don't know how it would play with ggplot either, can look

@dill right, just png

**Comment by sckott** [comment]
@dill works nicely, :+1:

**Pull request merged**
